title: 'mercury14.github.io'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
baseurl: "/myblog"
url: "https://mercury14.github.io"

header_pages:
  - index.md
  - about.md
  - simon.md
  
#theme: jekyll-theme-console

remote_theme: b2a3e8/jekyll-theme-console

style: light # dark (default), light or hacker

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed